apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notary.fullname" . }}
  labels:
    {{- include "notary.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "notary.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notary.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "notary.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-registration
          env:
            - name: ACCEPT_LICENSE
              value: "{{required "You must accept the license agreement to use this software." .Values.acceptLicense }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ required "notary[registration]: missing value for .Values.dockerImage.name" .Values.dockerImage.name }}:{{ required "notary[registration]: missing value for .Values.dockerImage.tag" .Values.dockerImage.tag }}"
          imagePullPolicy: {{ .Values.dockerImage.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          - |-
            ls -alr
            wget --tries=5 https://truststore.pki.rds.amazonaws.com/ap-southeast-1/ap-southeast-1-bundle.pem
            apk add openssl
            openssl x509 -outform der -in ap-southeast-1-bundle.pem -out ap-southeast-1-bundle.der
            mv ap-southeast-1-bundle.pem ap-southeast-1-bundle.der /opt/corda/workspace/certificates/
            cp notary-initial-registration.sh create-network-parameters-file.sh workspace/
            chmod +x workspace/*.sh
            workspace/notary-initial-registration.sh
            workspace/create-network-parameters-file.sh
          volumeMounts:
          - name: notary-conf
            mountPath: /opt/corda/workspace/node.conf
            subPath: node.conf
          - name: notary-conf
            mountPath: /opt/corda/notary-initial-registration.sh
            subPath: notary-initial-registration.sh
          - name: notary-conf
            mountPath: /opt/corda/create-network-parameters-file.sh
            subPath: create-network-parameters-file.sh
          - name: notary-certificates
            mountPath: /opt/corda/workspace/certificates
          - name: notary-nodeinfo
            mountPath: /opt/corda/workspace/additional-node-infos
          - name: notary-logs
            mountPath: /opt/corda/workspace/logs
          - name: pki-certs-keys
            mountPath: /opt/corda/workspace/DATA
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ required "notary[main]: missing value for .Values.dockerImage.name" .Values.dockerImage.name }}:{{ required "notary[main]: missing value for .Values.dockerImage.tag" .Values.dockerImage.tag }}"
          imagePullPolicy: {{ .Values.dockerImage.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          - |-
            wget --tries=5 https://truststore.pki.rds.amazonaws.com/ap-southeast-1/ap-southeast-1-bundle.pem
            mv ap-southeast-1-bundle.pem /opt/corda/workspace/certificates/
            ls -l /opt/corda/workspace/additional-node-infos
            ./startCorda.sh

            status=$?
            if [ "${status}" -ne "0" ]
            then
              echo "Node failed - exit code: ${status} (error)"
              echo
              echo "Going to sleep for requested 180 seconds to let you login and investigate."
              sleep 180
            fi
          volumeMounts:
          - name: notary-conf
            mountPath: /opt/corda/workspace/node.conf
            subPath: node.conf
          - name: notary-conf
            mountPath: /opt/corda/workspace/notary-initial-registration.sh
            subPath: notary-initial-registration.sh
          - name: notary-certificates
            mountPath: /opt/corda/workspace/certificates
          - name: notary-cordapps
            mountPath: /opt/corda/workspace/cordapps
          - name: notary-nodeinfo
            mountPath: /opt/corda/workspace/additional-node-infos
          - name: notary-logs
            mountPath: /opt/corda/workspace/logs
          - name: pki-certs-keys
            mountPath: /opt/corda/workspace/DATA
          env:
          - name: IDENTITY_MANAGER_ADDRESS
            value: "http://cenm-idman-ip.cenm:10000"
          - name: NETMAP_ADDRESS
            value: "http://cenm-nmap.cenm:10000"
          - name: TRUSTSTORE_PASSWORD
            value: "trust-store-password"
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.p2pPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end  }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.p2pPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end  }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.logsContainersEnabled }}
        - name: logs-notary
          image: "{{ required "notary[logs]: missing value for .Values.dockerImage.name" .Values.dockerImage.name }}:{{ required "notary[logs]: missing value for .Values.dockerImage.tag" .Values.dockerImage.tag }}"
          imagePullPolicy: {{ .Values.dockerImage.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          - |-
            cd /opt/corda/workspace/
            while true; do tail -f logs/*.log 2>/dev/null; sleep 5; done
            # in case sth went wrong just wait indefinitely ...
            tail -f /dev/null
          volumeMounts:
          - name: notary-logs
            mountPath: /opt/corda/workspace/logs
        {{- end  }}
      volumes:
      - name: notary-conf
        configMap:
          name: {{ .Values.prefix }}-notary-conf
      - name: notary-certificates
        persistentVolumeClaim:
          claimName: {{ .Values.prefix }}-notary-certificates
      - name: notary-cordapps
        persistentVolumeClaim:
          claimName: {{ .Values.prefix }}-notary-cordapps
      - name: notary-logs
        persistentVolumeClaim:
          claimName: {{ .Values.prefix }}-notary-logs
      - name: notary-nodeinfo
        persistentVolumeClaim:
          claimName: {{ .Values.prefix }}-notary-nodeinfo
      - name: pki-certs-keys
        persistentVolumeClaim:
          claimName: {{ .Values.prefix }}-pki-certs-keys
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
