---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-notary-nodeinfo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassShared }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNotaryNodeinfo }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-notary-certificates
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNotaryCertificate }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-notary-logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNotaryLogs }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cenm-notary-cordapps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cenm
  resources:
    requests:
      storage: 5Mi

