apiVersion: v1
kind: Service
metadata:
  name: {{ include "notary.fullname" . }}
  labels:
    {{- include "notary.labels" . | nindent 4 }}
spec:
# we need healthCheckNodePort set to get rid of logs pollution
{{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
{{- end }}
  ports:
    - port: {{ .Values.rpcSettingsAddressPort }}
      targetPort: {{ .Values.rpcSettingsAddressPort }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.sshdPort }}
      targetPort: {{ .Values.sshdPort }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "notary.selectorLabels" . | nindent 4 }}
