
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-signer-conf
  labels:
    {{ include "signer.labels" . | nindent 4 }}
data:
  run.sh: |+
    {{ tpl (.Files.Get "files/run.sh") . | nindent 4 }}

  signer-aws.conf: |+
    {{ tpl (.Files.Get "files/signer-aws.conf") . | nindent 4 }}

  getZoneToken.sh: |+
    {{ tpl (.Files.Get "files/getZoneToken.sh") . | nindent 4 }}

  customerCA.crt: |+
    {{ tpl (.Files.Get "files/customerCA.crt") . | nindent 4 }}
