---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cenm
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cenm-shared
provisioner: aws.io/aws-efs
allowVolumeExpansion: true
