# Default values for notary-ip.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  p2pPort: 40000
  sshdPort: 2223

healthCheckNodePort: 0
