
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-pki-conf
  labels:
    {{ include "pki.labels" . | nindent 4 }}
data:
  run.sh: |+
    {{ tpl (.Files.Get "files/run.sh") . | nindent 4 }}

  pki-aws.conf: |+
    {{ tpl (.Files.Get "files/pki-aws.conf") . | nindent 4 }}

  customerCA.crt: |+
    {{ tpl (.Files.Get "files/customerCA.crt") . | nindent 4 }}