apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pki.fullname" . }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pkiImage.repository }}:{{ .Values.pkiImage.tag }}"
          imagePullPolicy: {{ .Values.pkiImage.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          - |-
            set -x
            apt-get -qq -y update
            wget --tries=5 https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/EL7/cloudhsm-client-latest.el7.x86_64.rpm
            yum install ./cloudhsm-client-latest.el7.x86_64.rpm -y

            wget --tries=5 https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/EL7/cloudhsm-client-jce-latest.el7.x86_64.rpm
            yum install ./cloudhsm-client-jce-latest.el7.x86_64.rpm -y

            cd /opt/cenm
            mkdir bin
            cp CM-FILES/pki-aws.conf etc/pki-aws.conf
            cp CM-FILES/customerCA.crt /opt/cloudhsm/etc/customerCA.crt
            cp CM-FILES/run.sh bin/run.sh
            cp ../../pki-tool-jar/* bin/
            chmod +x bin/run.sh
            mkdir DATA/key-stores DATA/trust-stores DATA/crl-files

            /opt/cloudhsm/bin/configure -a "{{ .Values.pkiAWS.credentialsAmazon.eniIPAddress}}"
            /opt/cloudhsm/bin/cloudhsm_client /opt/cloudhsm/etc/cloudhsm_client.cfg >output.log 2>&1 &
            jobs

            bin/run.sh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: pki-certs-keys
            mountPath: /opt/cenm/DATA
          - name: pki-etc
            mountPath: /opt/cenm/etc
          - name: hsm-libs
            mountPath: /opt/cenm/HSM
          - name: pki-conf
            mountPath: /opt/cenm/CM-FILES/pki-aws.conf
            subPath: pki-aws.conf
          - name: pki-conf
            mountPath: /opt/cenm/CM-FILES/customerCA.crt
            subPath: customerCA.crt
          - name: pki-conf
            mountPath: /opt/cenm/CM-FILES/run.sh
            subPath: run.sh
      restartPolicy: OnFailure
      volumes:
        - name: pki-conf
          configMap:
            name: {{ .Values.prefix }}-pki-conf
        - name: pki-etc
          persistentVolumeClaim:
            claimName: {{ .Values.prefix }}-pki-etc
        - name: pki-certs-keys
          persistentVolumeClaim:
            claimName: {{ .Values.prefix }}-pki-certs-keys
        - name: hsm-libs
          persistentVolumeClaim:
            claimName: {{ .Values.prefix }}-hsm-libs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
