apiVersion: v1
kind: Service
metadata:
  name: {{ include "notary-ip.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  labels:
{{ include "notary-ip.labels" . | indent 4 }}
{{ include "cenm.labels" . | indent 4 }}
spec:
# we need Local policy and healthCheckNodePort set to get rid of logs pollution
{{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
{{- end }}
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: p2pport
    # - port: {{ .Values.service.sshdPort }}
    #   targetPort: {{ .Values.service.sshdPort }}
    #   protocol: TCP
    #   name: ssh
  selector:
    app.kubernetes.io/name: notary
    app.kubernetes.io/instance: {{ .Values.prefix }}-notary
